image:
  repository: busybox
  tag: latest
  pullPolicy: IfNotPresent
appMessage: "Shipping Service"
service:
  port: 80
serviceAccount:
  create: true
  name: ""
  annotations: {}
  automount: true

